<?php

use App\Models\DeductionType;
use App\Models\IncomeType;
use App\Models\LeaveType;
use App\Models\LoanType;

return [
    'income-types' => [
        'name' => 'Income Type',
        'model' => IncomeType::class,
        'primary_key' => 'income_type_id',
        'log_table' => 'tbl_income_types',
        'order' => ['income_type_code' => 'asc'],
        'search' => ['income_type_code', 'description'],
        'protected_codes' => ['BASC', 'OVRT', '13TH'],
        'with' => ['incomeClass'],
        'columns' => [
            ['key' => 'income_type_code', 'label' => 'Code'],
            ['key' => 'description', 'label' => 'Description'],
            ['key' => 'incomeClass.income_class', 'label' => 'Income Classification'],
            ['key' => 'is_non_taxable', 'label' => 'Non-Taxable', 'type' => 'yes_no'],
            ['key' => 'is_in_compensation_limit', 'label' => 'Compensation Limit', 'type' => 'yes_no'],
            ['key' => 'is_active', 'label' => 'Status', 'type' => 'boolean'],
        ],
        'fields' => [
            ['name' => 'income_type_code', 'label' => 'Income Type Code', 'type' => 'text', 'rules' => ['required', 'string', 'max:4'], 'unique' => true],
            ['name' => 'description', 'label' => 'Description', 'type' => 'text', 'rules' => ['required', 'string', 'max:45']],
            ['name' => 'income_class_id', 'label' => 'Income Classification', 'type' => 'select', 'source' => 'income_classes', 'rules' => ['required', 'integer', 'exists:lu_income_classes,income_class_id']],
            ['name' => 'is_non_taxable', 'label' => 'Allow Non-Taxable', 'type' => 'checkbox', 'rules' => ['sometimes', 'boolean']],
            ['name' => 'is_in_compensation_limit', 'label' => 'Include in Compensation Limit', 'type' => 'checkbox', 'rules' => ['sometimes', 'boolean']],
            ['name' => 'breakdown_in_ytd_report', 'label' => 'Monthly Breakdown in YTD Report', 'type' => 'checkbox', 'rules' => ['sometimes', 'boolean']],
            ['name' => 'is_default_basic', 'label' => 'Use in Cost Center Allocation Report as Default Income', 'type' => 'checkbox', 'rules' => ['sometimes', 'boolean']],
        ],
    ],
    'deduction-types' => [
        'name' => 'Deduction Type',
        'model' => DeductionType::class,
        'primary_key' => 'deduction_type_id',
        'log_table' => 'tbl_deduction_types',
        'order' => ['deduction_type_code' => 'asc'],
        'search' => ['deduction_type_code', 'description'],
        'always_active_codes' => ['PHIL', 'PHIM', 'PIBG', 'SSSP', 'SSMP'],
        'with' => ['govtTable'],
        'columns' => [
            ['key' => 'deduction_type_code', 'label' => 'Code'],
            ['key' => 'description', 'label' => 'Description'],
            ['key' => 'employer_amount', 'label' => 'Employer Amount', 'type' => 'decimal'],
            ['key' => 'is_valid_govt_deduction', 'label' => 'Valid as Govt Deduction', 'type' => 'yes_no'],
            ['key' => 'is_active', 'label' => 'Status', 'type' => 'boolean'],
        ],
        'fields' => [
            ['name' => 'deduction_type_code', 'label' => 'Deduction Type Code', 'type' => 'text', 'rules' => ['required', 'string', 'max:4'], 'unique' => true],
            ['name' => 'description', 'label' => 'Description', 'type' => 'text', 'rules' => ['required', 'string', 'max:45']],
            ['name' => 'employer_amount', 'label' => 'Employer Amount', 'type' => 'number', 'rules' => ['nullable', 'numeric', 'min:0']],
            ['name' => 'is_amount_percentage', 'label' => 'Amount is Percentage', 'type' => 'checkbox', 'rules' => ['sometimes', 'boolean']],
            ['name' => 'is_valid_govt_deduction', 'label' => 'Valid as Government Deduction', 'type' => 'checkbox', 'rules' => ['sometimes', 'boolean']],
            ['name' => 'govt_table_id', 'label' => 'Use Government Table', 'type' => 'select', 'source' => 'govt_tables', 'depends_on' => ['field' => 'is_valid_govt_deduction', 'value' => true], 'rules' => ['nullable', 'integer', 'exists:tbl_govt_tables,govt_table_id']],
        ],
    ],
    'loan-types' => [
        'name' => 'Loan Type',
        'model' => LoanType::class,
        'primary_key' => 'loan_type_id',
        'log_table' => 'tbl_loan_types',
        'order' => ['loan_type_code' => 'asc'],
        'search' => ['loan_type_code', 'description'],
        'with' => ['loanClass'],
        'columns' => [
            ['key' => 'loan_type_code', 'label' => 'Code'],
            ['key' => 'description', 'label' => 'Description'],
            ['key' => 'loanClass.loan_class', 'label' => 'Loan Classification'],
            ['key' => 'sss_loan_type', 'label' => 'SSS Loan Type'],
            ['key' => 'is_viewable', 'label' => 'Viewable in Payslip', 'type' => 'yes_no'],
            ['key' => 'is_active', 'label' => 'Status', 'type' => 'boolean'],
        ],
        'fields' => [
            ['name' => 'loan_type_code', 'label' => 'Loan Type Code', 'type' => 'text', 'rules' => ['required', 'string', 'max:4'], 'unique' => true],
            ['name' => 'description', 'label' => 'Description', 'type' => 'text', 'rules' => ['required', 'string', 'max:45']],
            ['name' => 'loan_class_id', 'label' => 'Loan Classification', 'type' => 'select', 'source' => 'loan_classes', 'rules' => ['required', 'integer', 'exists:lu_loan_classes,loan_class_id']],
            ['name' => 'sss_loan_type', 'label' => 'SSS Loan Type', 'type' => 'text', 'depends_on' => ['field' => 'loan_class_id', 'value' => '1'], 'rules' => ['nullable', 'string', 'max:1']],
            ['name' => 'is_viewable', 'label' => 'Is Viewable in Payslip', 'type' => 'checkbox', 'default' => true, 'rules' => ['sometimes', 'boolean']],
        ],
    ],
    'leave-types' => [
        'name' => 'Leave Type',
        'model' => LeaveType::class,
        'primary_key' => 'leave_type_id',
        'log_table' => 'tbl_leave_types',
        'order' => ['leave_type_code' => 'asc'],
        'search' => ['leave_type_code', 'description'],
        'protected_codes' => ['AWOL', 'LATE', 'UNDT'],
        'with' => ['computationBasis'],
        'columns' => [
            ['key' => 'leave_type_code', 'label' => 'Code'],
            ['key' => 'description', 'label' => 'Description'],
            ['key' => 'computationBasis.description', 'label' => 'Computation Basis'],
            ['key' => 'is_valid_as_earned_leave', 'label' => 'Earned Leave', 'type' => 'yes_no'],
            ['key' => 'is_valid_for_adjustment', 'label' => 'Adjustment', 'type' => 'yes_no'],
            ['key' => 'is_convertible_to_cash', 'label' => 'Convertible to Cash', 'type' => 'yes_no'],
            ['key' => 'hours_non_taxable', 'label' => 'Hours Non-Taxable', 'type' => 'decimal'],
            ['key' => 'is_active', 'label' => 'Is Active', 'type' => 'boolean'],
        ],
        'fields' => [
            ['name' => 'leave_type_code', 'label' => 'Leave Type Code', 'type' => 'text', 'rules' => ['required', 'string', 'max:4'], 'unique' => true],
            ['name' => 'description', 'label' => 'Description', 'type' => 'text', 'rules' => ['required', 'string', 'max:45']],
            ['name' => 'computation_basis_id', 'label' => 'Computation Basis', 'type' => 'select', 'source' => 'computation_basis', 'rules' => ['required', 'integer', 'exists:tbl_computation_basis,computation_basis_id']],
            ['name' => 'leave_apply_to_id', 'label' => 'Apply To', 'type' => 'select', 'source' => 'leave_apply_to', 'rules' => ['nullable', 'integer', 'exists:tbl_leave_apply_to,leave_apply_to_id']],
            ['name' => 'late_undertime_leave_id', 'label' => 'Is Late/Undertime Leave?', 'type' => 'select', 'source' => 'late_undertime_leaves', 'rules' => ['nullable', 'integer', 'exists:lu_late_undertime_leaves,late_undertime_leave_id']],
            ['name' => 'is_valid_as_earned_leave', 'label' => 'Valid as Earned Leave', 'type' => 'checkbox', 'rules' => ['sometimes', 'boolean']],
            ['name' => 'is_valid_for_adjustment', 'label' => 'Valid for Adjustment', 'type' => 'checkbox', 'rules' => ['sometimes', 'boolean']],
            ['name' => 'is_breakdown_in_report', 'label' => 'Breakdown in Report', 'type' => 'checkbox', 'rules' => ['sometimes', 'boolean']],
            ['name' => 'is_convertible_to_cash', 'label' => 'Convertible to Cash', 'type' => 'checkbox', 'rules' => ['sometimes', 'boolean']],
            ['name' => 'hours_non_taxable', 'label' => 'Hours Non-Taxable', 'type' => 'number', 'depends_on' => ['field' => 'is_convertible_to_cash', 'value' => true], 'rules' => ['nullable', 'numeric', 'min:0']],
            ['name' => 'is_active', 'label' => 'Is Active', 'type' => 'checkbox', 'default' => true, 'rules' => ['sometimes', 'boolean']],
        ],
    ],
];
